GET http://localhost:3000

###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "name": "Ali",
    "email":"Ali123@gmail.com",
    "password": "demo123",
    "role": "worker"
}
###
POST http://localhost:3000/auth/login
Content-Type: application/json

{   
    "email":"Ali123@gmail.com",
    "password": "demo123"
}

###
POST http://localhost:3000/task/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkODZiNDA4YS04MGEyLTQyOGMtYjhjMC01MjA5MjFjNGZhYzIiLCJuYW1lIjoiSnVuZSIsImVtYWlsIjoiSnVuZXQxMjNAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzg2Nzc4MTc3LCJleHAiOjE3ODY4NjQ1Nzd9.hjyX0UpEx2-HFSWsuZjLiv5GgHjR3gpC6D4VAv8rcjM

 {
    "title": "WORK ON DESIGN",
    "description": "DOCUMENT IS MISSING IN ATTACHEMENT", 
    "assignedTo": "4e3a9d2b-bc84-4837-9c0b-e7e070ce8002",
    "createdBy": "d86b408a-80a2-428c-b8c0-520921c4fac2"
 }

###
GET http://localhost:3000/task
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkODZiNDA4YS04MGEyLTQyOGMtYjhjMC01MjA5MjFjNGZhYzIiLCJuYW1lIjoiSnVuZSIsImVtYWlsIjoiSnVuZXQxMjNAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzg2Nzc4ODgzLCJleHAiOjE3ODY4NjUyODN9.RzWOeXBh5tYqmVoTB0s_QC736zhj2UhhOKsZXcuuN18

###
GET http://localhost:3000/task/61dd1f62-d0d1-41cd-acc9-a29aaec636b9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkODZiNDA4YS04MGEyLTQyOGMtYjhjMC01MjA5MjFjNGZhYzIiLCJuYW1lIjoiSnVuZSIsImVtYWlsIjoiSnVuZXQxMjNAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzg2NTI5NDA5LCJleHAiOjE3ODY2MTU4MDl9.DhEUwpsEtFGg8aIizYMeGSkT8z-i_NdqTeTz9eblX3A 

###
PATCH http://localhost:3000/task/3226f398-254d-4589-beb9-19886c61c2fc
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkODZiNDA4YS04MGEyLTQyOGMtYjhjMC01MjA5MjFjNGZhYzIiLCJuYW1lIjoiSnVuZSIsImVtYWlsIjoiSnVuZXQxMjNAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzg2NTI5NDA5LCJleHAiOjE3ODY2MTU4MDl9.DhEUwpsEtFGg8aIizYMeGSkT8z-i_NdqTeTz9eblX3A

 {
    "id":"3226f398-254d-4589-beb9-19886c61c2fc", 
    "status":"done"
 }

###
DELETE http://localhost:3000/task/78de784f-cd3d-4d87-b081-ae89ad861c2d
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkODZiNDA4YS04MGEyLTQyOGMtYjhjMC01MjA5MjFjNGZhYzIiLCJuYW1lIjoiSnVuZSIsImVtYWlsIjoiSnVuZXQxMjNAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzg2NTI5NDA5LCJleHAiOjE3ODY2MTU4MDl9.DhEUwpsEtFGg8aIizYMeGSkT8z-i_NdqTeTz9eblX3A  